- name: clean out all datadirs
  file: path="{{ item }}" state=absent
  when: destroy is defined
  with_items:
    - /opt/consul/data
    - /opt/nomad/data
    
- name: clean out all datadirs
  file: path="{{ item }}" state=directory
  when: destroy is defined
  with_items:
    - /opt/consul/data
    - /opt/nomad/data

- name: setup consul templates
  template: src="consul/{{ item }}" dest="/etc/consul.d"
  notify: restart consul
  with_items:
    - consul-default.json
    - consul-server.json

- name: join consul cluster
  shell: /usr/local/bin/consul join {{ hostvars[item]['ansible_default_ipv4']['address'] }}:8301
  with_items: "{{ play_hosts }}"
  run_once: true

- name: setup vault templates
  template: src="vault/{{ item }}" dest="/etc/vault.d"
  notify: restart vault
  with_items:
    - vault-consul.hcl
    - vault-no-tls.hcl
    
- name: setup vault templates
  template: src="nomad/{{ item }}" dest="/etc/nomad.d"
  notify: restart nomad
  with_items:
    - nomad-client.hcl
    - nomad-consul.hcl
    - nomad-default.hcl
    - nomad-server.hcl