- name: setup consul templates
  template: src="{{ item }}" dest="/etc/nomad.d"
  notify: restart consul
  with_items:
    - consul-default.json
    - consul-server.json

- name: join consul cluster
  shell: consul join {{ hostvars[item]['ansible_default_ipv4']['address'] }}:8301
  with_items: "{{ play_hosts }}"
  run_once: true

- name: setup vault templates
  template: src="{{ item }}" dest="/etc/nomad.d"
  notify: restart vault
  with_items:
    - vault-consul.hcl
    - vault-no-tls.hcl
    
- name: setup vault templates
  template: src="{{ item }}" dest="/etc/nomad.d"
  notify: restart nomad
  with_items:
    - nomad-client.hcl
    - nomad-consul.hcl
    - nomad-default.hcl
    - nomad-server.hcl